# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esettings.proto\"l\n\nCoordinate\x12\x0e\n\x06point1\x18\x01 \x01(\x02\x12\x0e\n\x06point2\x18\x02 \x01(\x02\x12\x0e\n\x06point3\x18\x03 \x01(\x02\x12\x0e\n\x06point4\x18\x04 \x01(\x02\x12\x0e\n\x06point5\x18\x05 \x01(\x02\x12\x0e\n\x06point6\x18\x06 \x01(\x02\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\x9c\x01\n\x07Message\x12\x1b\n\x08\x61ligment\x18\x01 \x01(\x0e\x32\t.Aligment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x06\x63lasss\x18\x03 \x01(\x0e\x32\t.ShipType\x12\x0e\n\x06length\x18\x04 \x01(\x05\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x19\n\x07officer\x18\x07 \x03(\x0b\x32\x08.Officer*\x1f\n\x08\x41ligment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01*_\n\x08ShipType\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05\x32:\n\x0eGettingMessage\x12(\n\x0bSendMessage\x12\x0b.Coordinate\x1a\x08.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'settings_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALIGMENT']._serialized_start=351
  _globals['_ALIGMENT']._serialized_end=382
  _globals['_SHIPTYPE']._serialized_start=384
  _globals['_SHIPTYPE']._serialized_end=479
  _globals['_COORDINATE']._serialized_start=18
  _globals['_COORDINATE']._serialized_end=126
  _globals['_OFFICER']._serialized_start=128
  _globals['_OFFICER']._serialized_end=190
  _globals['_MESSAGE']._serialized_start=193
  _globals['_MESSAGE']._serialized_end=349
  _globals['_GETTINGMESSAGE']._serialized_start=481
  _globals['_GETTINGMESSAGE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
